# Generated by Django 2.1.3 on 2020-06-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='image23',
        ),
    ]
